# Generated by Django 4.1.2 on 2022-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=50)),
                ('estacion_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Estaciones',
            },
        ),
    ]
