# Generated by Django 4.1.2 on 2022-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorhorarios', '0002_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='salidas',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='slug (autopopulate on save)'),
        ),
    ]
