# Generated by Django 4.1.2 on 2022-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorhorarios', '0003_ruta_salidas_alter_ruta_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='json_data',
            new_name='raw_json_data',
        ),
        migrations.AddField(
            model_name='ruta',
            name='empresa',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='kms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='llegadas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='notas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='num_rutas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='periodicidad',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='servicio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='salidas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
