# Generated by Django 4.1.2 on 2022-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorhorarios', '0004_rename_json_data_ruta_raw_json_data_ruta_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='raw_json_periodicidad',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='empresa',
            field=models.JSONField(blank=True, null=True, verbose_name='Empresa (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='kms',
            field=models.JSONField(blank=True, null=True, verbose_name='Kms (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='llegadas',
            field=models.JSONField(blank=True, null=True, verbose_name='Llegadas (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='notas',
            field=models.JSONField(blank=True, null=True, verbose_name='Notas (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='num_rutas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de Rutas del Trayecto (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='periodicidad',
            field=models.JSONField(blank=True, null=True, verbose_name='Periodicidad (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='salidas',
            field=models.JSONField(blank=True, null=True, verbose_name='Salidas (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='servicio',
            field=models.JSONField(blank=True, null=True, verbose_name='Servicio (autopopulate on save)'),
        ),
    ]
