# Generated by Django 4.1.2 on 2022-11-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorhorarios', '0005_ruta_raw_json_periodicidad_alter_ruta_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='ruta_valida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='slug_vuelta',
            field=models.SlugField(allow_unicode=True, default=None, unique=True, verbose_name='slug (autopopulate on save)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='raw_json_periodicidad',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
