# Generated by Django 4.1.2 on 2022-11-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorhorarios', '0006_ruta_ruta_valida_ruta_slug_vuelta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='raw_json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='slug_vuelta',
            field=models.SlugField(allow_unicode=True, default=None, unique=True, verbose_name='slug ruta de vuelta (autopopulate on save)'),
        ),
    ]
