# Generated by Django 4.1.2 on 2022-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorhorarios', '0008_rename_periodicidad_ruta_fecha_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='periodicidad',
            field=models.JSONField(blank=True, null=True, verbose_name='Periodicidad (autopopulate on save)'),
        ),
    ]
